trigger: none
pr:
  branches:
    include: [ main ]
  autoCancel: "true"
  drafts: "true"

jobs:

  - job: nbval
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "95"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"

    pool: azure-gpus-spot
    # this need to have installed docker in the base image...
    container:
      # base ML image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.9"
      # image: "pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime"
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --shm-size=32g --name ci-container -v /usr/bin/docker:/tmp/docker:ro"

    variables:
      ACCELERATOR: CPU,GPU
      PATH_DATASETS: "$(Build.Repository.LocalPath)/.datasets"

    steps:

    - bash: |
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        python --version
        pip list | grep torch
      displayName: 'Image info & NVIDIA'

    - script: |
        /tmp/docker exec -t -u 0 ci-container \
        sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
      displayName: 'Install Sudo in container (thanks Microsoft!)'

    - bash: |
        set -e
        sudo apt-get update -q --fix-missing
        sudo apt install -y tree ffmpeg
        pip install --upgrade pip
        pip --version
        pip install --requirement requirements.txt
        pip install --requirement requirements/data.txt
        sudo pip uninstall -y horovod
        sudo pip uninstall -y torchtext  # FIXME: this is hotfix for https://github.com/Lightning-AI/lightning/pull/12676
        pip list
      displayName: 'Install dependencies'

    - bash: |
        python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu > 0, f'GPU: {mgpu}'"
      displayName: 'Sanity check'

    - bash: |
        mkdir $(PATH_DATASETS)
        head=$(git rev-parse origin/main)
        printf "Head: $head\n"
        git diff --name-only $head --output=target-diff.txt
        python .actions/assistant.py group-folders target-diff.txt
        printf "Changed folders:\n"
        cat changed-folders.txt
      displayName: 'Process folders'

    - script: |
        COUNT=$(python -c "lines = open('changed-folders.txt').readlines() ; print(len(lines))")
        printf "Changed folders: $COUNT\n"
        echo "##vso[task.setvariable variable=folders;isOutput=true]$COUNT"
      name: changed

    - bash: |
        while IFS= read -r line; do
            python .actions/assistant.py convert-ipynb $line
        done <<< $(cat changed-folders.txt)
      condition: gt(variables['changed.folders'], 0)
      displayName: 'Generate notebook'

    - bash: |
        set -e
        while IFS= read -r line; do
            python .actions/assistant.py bash-test $line
            cat .actions/_ipynb-test.sh
            bash .actions/_ipynb-test.sh
        done <<< $(cat changed-folders.txt)
      condition: and(succeeded(), gt(variables['changed.folders'], 0))
      env:
        KAGGLE_USERNAME: $(KAGGLE_USERNAME)
        KAGGLE_KEY: $(KAGGLE_KEY)
      displayName: 'PyTest notebook'
