title: "Tutorial 9: Normalizing Flows for Image Modeling"
author: Phillip Lippe
created: 2021-06-07
updated: 2023-03-14
license: CC BY-SA
build: 0
tags:
  - Image
description: |
  In this tutorial, we will take a closer look at complex, deep normalizing flows.
  The most popular, current application of deep normalizing flows is to model datasets of images.
  As for other generative models, images are a good domain to start working on because
  (1) CNNs are widely studied and strong models exist,
  (2) images are high-dimensional and complex,
  and (3) images are discrete integers.
  In this tutorial, we will review current advances in normalizing flows for image modeling,
  and get hands-on experience on coding normalizing flows.
  Note that normalizing flows are commonly parameter heavy and therefore computationally expensive.
  We will use relatively simple and shallow flows to save computational cost and allow you to run the notebook on CPU,
  but keep in mind that a simple way to improve the scores of the flows we study here is to make them deeper.
  This notebook is part of a lecture series on Deep Learning at the University of Amsterdam.
  The full list of tutorials can be found at https://uvadlc-notebooks.rtfd.io.
requirements:
  - torchvision
  - matplotlib
  - seaborn
  - tabulate
  - lightning>=2.0.0rc0
accelerator:
  - CPU
  - GPU
