title: TPU training with PyTorch Lightning
author: PL team
created: 2020-12-21
updated: 2021-06-25
license: CC BY-SA
tags:
  - Image
  - TPU
description: In this notebook, we'll train a model on TPUs. Updating one Trainer flag is all you need for that.
  The most up to documentation related to TPU training can be found
  [here](https://pytorch-lightning.readthedocs.io/en/latest/advanced/tpu.html).
requirements:
  - torchvision
accelerator:
  - TPU
